//! PMIx C bindings generated by `bindgen`.
//!
//! This file includes the auto-generated bindings from `OUT_DIR/bindings.rs`
//! (produced by `build.rs` via `bindgen::Builder`). The generated bindings
//! cover the full PMIx 5.0 C API surface — types, constants, and function
//! declarations.
//!
//! No unit tests are defined here — the bindings are validated indirectly
//! through the safe wrapper modules (`data_ops`, `events`, `fabric`, etc.)
//! and through compile-time checks below.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unnecessary_transmutes)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    /// Verify that critical PMIx status constants are present in the generated bindings.
    /// If this test fails, the bindgen output is stale or the PMIx headers changed.
    #[test]
    fn test_pmix_status_constants_present() {
        use crate::ffi::*;
        // Core status constants must exist
        let _: u32 = PMIX_SUCCESS;
        let _: i32 = PMIX_ERROR;
        let _: i32 = PMIX_ERR_NOT_FOUND;
        let _: i32 = PMIX_ERR_INIT;
    }

    /// Verify that key PMIx data type constants are present.
    #[test]
    fn test_pmix_data_types_present() {
        use crate::ffi::*;
        let _: u32 = PMIX_BOOL;
        let _: u32 = PMIX_INT;
        let _: u32 = PMIX_STRING;
        let _: u32 = PMIX_SIZE;
    }

    /// Verify that PMIx scope constants are present.
    #[test]
    fn test_pmix_scope_constants_present() {
        use crate::ffi::*;
        let _: u32 = PMIX_LOCAL;
        let _: u32 = PMIX_PROC;
        let _: u32 = PMIX_GLOBAL;
    }

    /// Verify pmix_value_t struct layout — type_ and data fields exist.
    #[test]
    fn test_pmix_value_t_layout() {
        use crate::ffi::*;
        let _type_offset = std::mem::offset_of!(pmix_value, type_);
        let _data_offset = std::mem::offset_of!(pmix_value, data);
        // type_ comes before data
        assert!(
            _type_offset < _data_offset,
            "pmix_value field order unexpected"
        );
    }

    /// Verify pmix_proc_t struct layout — nspace then rank.
    #[test]
    fn test_pmix_proc_t_layout() {
        use crate::ffi::*;
        let _ns_offset = std::mem::offset_of!(pmix_proc, nspace);
        let _rank_offset = std::mem::offset_of!(pmix_proc, rank);
        // nspace comes first, then rank
        assert!(
            _ns_offset < _rank_offset,
            "pmix_proc field order unexpected"
        );
    }

    /// Verify bindgen version constraints compile (sanity check on struct sizes).
    #[test]
    fn test_pmix_proc_size() {
        use crate::ffi::*;
        // pmix_proc = nspace (PMIX_MAX_NSLEN=255 bytes + null) + rank (4 bytes)
        // bindgen asserts size_of::<pmix_proc>() == 260
        assert_eq!(
            std::mem::size_of::<pmix_proc>(),
            260,
            "pmix_proc size mismatch — bindgen output may be stale"
        );
    }

    /// Verify the pmix_info_t struct has key and value fields.
    #[test]
    fn test_pmix_info_t_fields() {
        use crate::ffi::*;
        let _key_offset = std::mem::offset_of!(pmix_info, key);
        let _val_offset = std::mem::offset_of!(pmix_info, value);
        assert!(
            _key_offset < _val_offset,
            "pmix_info field order unexpected"
        );
    }
}
